# Site settings
title: "Vishal Raveendranathan"
email: vishal.raveendranathan@gmail.com
description: "Vishal's Blog"
baseurl: ""
url: "https://vbotics.github.io"
title_description: "PhD Research Candidate, University of Groningen"
title_image: "https://s.gravatar.com/avatar/e8359f13ae38572bdef4baf81262ad62?s=500&d=mm"
google_analytics: "UA-48718787-1"
disqus_account: vishalslaboratory
github_repository: https://github.com/vbotics/vbotics.github.io
addthis_id: ra-5c897a441c906727
post_limit: 5

# Social usernames/URLs
twitter_username: vishal_R_vishal
github_username:  vbotics
instagram_username: vishal.raveendranathan
reddit_username: 
linkedin_link: https://www.linkedin.com/in/vishalraveendranathan/
google_plus_link:
stackoverflow_link: https://stackexchange.com/users/5529681/vishal-r
xing_link:
facebook_link: https://www.facebook.com/vishal.raveendranathan

# Footer
footer_left: "Theme with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
